export const SRI_LANKAN_CITIES = [
  'Colombo',
  'Nugegoda',
  'Rajagiriya',
  'Kandy',
  'Galle',
  'Negombo',
  'Kotte',
  'Moratuwa',
  'Kurunegala',
  'Jaffna',
  'Battaramulla',
  'Malabe',
];

export const ATS_PLATFORMS = [
  'greenhouse',
  'bamboohr',
  'lever',
  'workday',
  'icims',
  'smartrecruiters',
  'recruitee',
  null,
];

// Used only by seo.seeder.ts for SeoRole slugs. Job.roleCategory itself is
// now seeded from ALL_CATEGORIES in @careerslk/types (see jobs.seeder.ts),
// which is decoupled from this older, flatter list.
export const ROLE_CATEGORIES = [
  'Engineering',
  'Design',
  'Product',
  'Marketing',
  'Sales',
  'Human Resources',
  'Finance',
  'Operations',
  'Customer Support',
  'Data & Analytics',
  'Legal',
  'Business Analyst',
];

export const DEPARTMENTS = [
  'Engineering',
  'Product',
  'Design',
  'Marketing',
  'People & Culture',
  'Finance',
  'Operations',
  'Customer Success',
  'Data',
  'Legal',
  'Admin',
];

export const EXPLICIT_SKILLS = [
  'TypeScript',
  'JavaScript',
  'React',
  'Next.js',
  'Node.js',
  'NestJS',
  'PostgreSQL',
  'Prisma',
  'Docker',
  'Kubernetes',
  'AWS',
  'Python',
  'Java',
  'Spring Boot',
  'GraphQL',
  'Redis',
  'Figma',
  'Adobe XD',
  'SEO',
  'Google Analytics',
  'Excel',
  'Power BI',
  'Salesforce',
  'SAP',
];

export const KEYWORD_POOL = [
  'remote',
  'hybrid',
  'on-site',
  'full-time',
  'part-time',
  'internship',
  'entry-level',
  'senior-level',
  'associate-level',
  'manager-level',
  'engineering',
  'design',
  'marketing',
  'finance',
  'human-resources',
  'sales',
  'operations',
  'urgent-hiring',
  'walk-in-interview',
  'graduate-trainee',
];

export const COMPANY_NAME_PARTS = {
  prefixes: [
    'Ceylon',
    'Lanka',
    'Indo',
    'Global',
    'Prime',
    'Nova',
    'Bright',
    'Summit',
    'Bluewave',
    'Redberry',
    'Silverline',
    'Skyline',
  ],
  suffixes: [
    'Technologies',
    'Solutions',
    'Holdings',
    'Group',
    'Software',
    'Systems',
    'Ventures',
    'Labs',
    'Digital',
    'Enterprises',
    'Networks',
    'Innovations',
  ],
};

export const SALARY_CURRENCY = 'LKR';
