export const ATS_PLATFORMS = [
  'greenhouse',
  'bamboohr',
  'lever',
  'workday',
  'icims',
  'smartrecruiters',
  'recruitee',
  null,
];

export const EXPLICIT_SKILLS = [
  'TypeScript',
  'JavaScript',
  'React',
  'Next.js',
  'Node.js',
  'NestJS',
  'PostgreSQL',
  'Prisma',
  'Docker',
  'Kubernetes',
  'AWS',
  'Python',
  'Java',
  'Spring Boot',
  'GraphQL',
  'Redis',
  'Figma',
  'Adobe XD',
  'SEO',
  'Google Analytics',
  'Excel',
  'Power BI',
  'Salesforce',
  'SAP',
];

export const KEYWORD_POOL = [
  'remote',
  'hybrid',
  'on-site',
  'full-time',
  'part-time',
  'internship',
  'entry-level',
  'senior-level',
  'associate-level',
  'manager-level',
  'engineering',
  'design',
  'marketing',
  'finance',
  'human-resources',
  'sales',
  'operations',
  'urgent-hiring',
  'walk-in-interview',
  'graduate-trainee',
];

export const COMPANY_NAME_PARTS = {
  prefixes: [
    'Ceylon',
    'Lanka',
    'Indo',
    'Global',
    'Prime',
    'Nova',
    'Bright',
    'Summit',
    'Bluewave',
    'Redberry',
    'Silverline',
    'Skyline',
  ],
  suffixes: [
    'Technologies',
    'Solutions',
    'Holdings',
    'Group',
    'Software',
    'Systems',
    'Ventures',
    'Labs',
    'Digital',
    'Enterprises',
    'Networks',
    'Innovations',
  ],
};

export const SALARY_CURRENCY = 'LKR';
