packages:
  - apps/*
  - packages/*
allowBuilds:
  '@nestjs/core': true
  '@playwright/browser-chromium': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  bcrypt: true
  msgpackr-extract: true
  msw: true
  prisma: true
  sharp: false
  unrs-resolver: false
